apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-plugins-cache
  labels:
    type: plugin-cache
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  nfs:
    server: 100.75.219.111
    path: /mnt/nfs-minecraft/plugins-cache

---


apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plugins-cache
  namespace: minecraft-servers
  labels:
    type: plugin-cache
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  volumeName: pv-plugins-cache